name: dewater
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas>=2.0
  - numpy<2 
  - matplotlib 
  - openpyxl
  - xlrd
  - jupyter 
  - notebook 
  - scipy 
  - shapely
  - rtree
  - pyproj>=2.0
  - pyshp
  - psutil
  - git
  - nbconvert
  - hdf5
  - modflowapi
  - pip
  - pip:
       - -e ./dependencies/flopy
       - -e ./dependencies/pyemu
       - pypestutils == 0.3.0
       #- mf6adj


